name: MathUtility using Maven, CI(GitHub Action) © 2023 Tanu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
  - name: Check-out repository # Lấy code từ kho thảy vào máy ảo của GitHub chuẩn bị build ở bước sau
    uses: actions/checkout@v3
  - name: Set up JDK 20 - Mượn JDK và cài vào Server Ubuntu của Mỹ mà GitHub tạm cho mượn
    uses: actions/setup-java@v3
    with:
      java-version: '20'
      distribution: 'temurin'
      cache: maven
  - name: Build with Maven
    run: mvn -B package --file pom.xml
  - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
    run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
  - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
    uses: actions/upload-artifact@v1
    with:
      name: ban-gai.zip #Bản build .JAR .WAR đc nén lại thành file .zip để tải về
      path: staging
